id: PF011F48D
initial_creation_type: input
source_metadata:
  Title: Caryāgitikoṣaḥ upodghātaḥ
  Editor: '-'
  Publisher: Visva Bharati
  Place of Publication: Santiniketan
  Year: '1956'
  Upodghātaḥ:
    Text Version: Romanized
    Input Personnel: Pundarika Shakya
    Input Date: '2015'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:58:23.345724'
last_modified_at: '2022-03-08T16:58:23.345731'
